# Generated by Django 3.1.7 on 2021-04-01 10:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_name', models.CharField(help_text='Название ресторана.', max_length=30, verbose_name='Название.')),
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(help_text='Адрес ресторана.', max_length=150, verbose_name='Адрес.')),
                ('description_restaurant', models.CharField(help_text='Описание ресторана.', max_length=150, verbose_name='Описание.')),
                ('average_check_restaurant', models.IntegerField(help_text='Средний чек.', verbose_name='Средний чек.')),
            ],
            options={
                'verbose_name': 'Ресторан.',
                'verbose_name_plural': 'Рестораны.',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_restaurant', models.ImageField(help_text='Выберите изображение.', upload_to='', verbose_name='Изображения.')),
                ('order', models.IntegerField(default=1, help_text='Порядковый номер создается автоматически.', verbose_name='Порядковый номер.')),
                ('restaurant_id_image', models.ForeignKey(default='Ресторан.', help_text='Выберите ресторан.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.restaurant', verbose_name='Изображение ресторана.')),
            ],
            options={
                'verbose_name': 'Картинка.',
                'verbose_name_plural': 'Картинки.',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название.')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.restaurant', verbose_name='Меню.')),
            ],
            options={
                'verbose_name': 'Блюдо.',
                'verbose_name_plural': 'Блюда.',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(help_text='Оставьте отзыв о ресторане.', max_length=255, verbose_name='Отзыв.')),
                ('user_name', models.CharField(help_text='Напишите выдуманное имя для отзыва.', max_length=25, verbose_name='Имя пользователя.')),
                ('stars', models.IntegerField(help_text='Оценка ресторана по 5 бальной шкале.', verbose_name='Оценка.')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создается автоматически.', verbose_name='Дата.')),
                ('order', models.IntegerField(default=9999, help_text='Порядковый номер создается автоматически.', verbose_name='Порядковый номер.')),
                ('id_restaurant', models.ForeignKey(help_text='Выберите ресторан.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mainapp.restaurant', verbose_name='Для какого ресторана.')),
            ],
            options={
                'verbose_name': ' отзыв.',
                'verbose_name_plural': 'Отзывы.',
                'ordering': ('order',),
                'unique_together': {('id_restaurant', 'order')},
            },
        ),
    ]
