# Generated by Django 3.1.7 on 2021-04-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210412_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description_restaurant',
            field=models.CharField(help_text='Описание кухни ресторана', max_length=150, verbose_name='Описание кухни'),
        ),
    ]
