# Generated by Django 3.2 on 2021-04-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210408_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='check',
            field=models.IntegerField(default=0, help_text='Цена блюда.', verbose_name='Цена.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='about_restaurant',
            field=models.CharField(default='', help_text='Полное описание ресторана.', max_length=250, verbose_name='Описание ресторана.'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description_restaurant',
            field=models.CharField(help_text='Описание кухни ресторана.', max_length=50, verbose_name='Описание кухни.'),
        ),
    ]
