# Generated by Django 3.1.7 on 2021-04-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210412_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='about_restaurant',
            field=models.CharField(default='', help_text='Полное описание ресторана', max_length=3000, verbose_name='Описание ресторана'),
        ),
    ]
