# Generated by Django 3.1.7 on 2021-04-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210414_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='about_restaurant',
            field=models.TextField(default='', help_text='Полное описание ресторана', max_length=3000, verbose_name='Описание ресторана'),
        ),
    ]
