# Generated by Django 3.2 on 2021-04-09 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210408_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Ресторан', 'verbose_name_plural': 'Рестораны'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('-order',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='check',
            field=models.IntegerField(default=0, help_text='Цена блюда', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.restaurant', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_restaurant',
            field=models.ImageField(help_text='Выберите изображение', upload_to='', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=1, help_text='Порядковый номер создается автоматически', verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='image',
            name='restaurant_id_image',
            field=models.ForeignKey(default='Ресторан', help_text='Выберите ресторан', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.restaurant', verbose_name='Изображение ресторана'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='about_restaurant',
            field=models.CharField(default='', help_text='Полное описание ресторана', max_length=250, verbose_name='Описание ресторана'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_check_restaurant',
            field=models.IntegerField(help_text='Средний чек', verbose_name='Средний чек'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description_restaurant',
            field=models.CharField(help_text='Описание кухни ресторана', max_length=50, verbose_name='Описание кухни'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(help_text='Адрес ресторана', max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(help_text='Название ресторана', max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создается автоматически', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='id_restaurant',
            field=models.ForeignKey(help_text='Выберите ресторан', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mainapp.restaurant', verbose_name='Для какого ресторана'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='order',
            field=models.IntegerField(default=9999, help_text='Порядковый номер создается автоматически', verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(help_text='Оставьте отзыв о ресторане', max_length=255, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='stars',
            field=models.IntegerField(help_text='Оценка ресторана по 5 бальной шкале', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user_name',
            field=models.CharField(help_text='Напишите выдуманное имя для отзыва', max_length=25, verbose_name='Имя пользователя'),
        ),
    ]
