# Generated by Django 3.2.3 on 2021-05-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(help_text='Оставьте отзыв о ресторане', max_length=1000, verbose_name='Отзыв'),
        ),
    ]
